KhumaloCraft/Pages/AboutUsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KhumaloCraft.Pages
{
    public class AboutUsPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

KhumaloCraft/Pages/AdminPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using KhumaloCraft.Models;
using KhumaloCraft.Data;
using Microsoft.Extensions.Logging;

namespace KhumaloCraft.Pages
{
    public class AdminPageModel : PageModel
    {
        private readonly KhumaloCraftContext _context;
        private readonly ILogger<AdminPageModel> _logger;

        public AdminPageModel(KhumaloCraftContext context, ILogger<AdminPageModel> logger)
        {
            _context = context;
            _logger = logger;
        }

        public IList<Transactions> Orders { get; set; }
        public IList<User> users { get; set; }
        public IList<Product> Products { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            Orders = await _context.Transactions.ToListAsync();
            users = await _context.User.ToListAsync();
            Products = await _context.Product.ToListAsync();
            return Page();
        }

        public IActionResult OnPostProcessOrder()
        {
            var id = Request.Form["id"];

            _logger.LogInformation("ID : " + id);

            var orderId = int.Parse(id);

            var order = _context.Transactions.Find(orderId);

            if (order != null)
            {
                order.Processed = true;
                _context.SaveChanges();
            }
            else
            {
                _logger.LogWarning($"Order with ID {orderId} not found.");
            }

            return RedirectToPage("/AdminPage");
        }

        public IActionResult OnPostAdminStatus()
        {
            var userid = Request.Form["userid"];

            var tempid = int.Parse(userid);

            var admin = _context.User.Find(tempid);

            if (admin != null)
            {
                admin.Admin = true;
                _context.SaveChanges();
            }
            else
            {
                _logger.LogWarning($"User with ID {tempid} not found.");
            }


            return RedirectToPage("/AdminPage");
        }

        public IActionResult OnPostDeleteProduct()
        {

            var tempid = Request.Form["productid"];
            var productid = int.Parse(tempid);
            var product = _context.Product.Find(productid);

            if (product != null)
            {
                _context.Product.Remove(product);
                _context.SaveChanges();
            }

            return RedirectToPage("/AdminPage");
        }

        public IActionResult OnPostAddItem()
        {

            var name = Request.Form["name"];
            var description = Request.Form["description"];
            var quantity = int.Parse(Request.Form["quantity"]);
            var price = Math.Round(double.Parse(Request.Form["price"]), 2);
            var category = Request.Form["category"]; 

            var newProduct = new Product
            {
                Name = name,
                Description = description,
                Quantity = quantity,
                Price = price,
                Category = category
            };

            _context.Product.Add(newProduct);
            _context.SaveChanges();
            
            return RedirectToPage("/AdminPage");
        }

    }
}

KhumaloCraft/Pages/ContactUsPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KhumaloCraft.Pages
{
    public class ContactUsPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

KhumaloCraft/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace KhumaloCraft.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

KhumaloCraft/Pages/HomePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KhumaloCraft.Pages
{
    public class HomePageModel : PageModel
    {
        private readonly ILogger<HomePageModel> _logger;

        public HomePageModel(ILogger<HomePageModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

KhumaloCraft/Pages/Index.cshtml.cs
using KhumaloCraft.Data;
using KhumaloCraft.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KhumaloCraft.Pages
{
    public class IndexModel : PageModel
    {
        private readonly KhumaloCraftContext _context;
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger, KhumaloCraftContext context)
        {
            _logger = logger;
            _context = context;
        }

        public void OnGet()
        {

        }

        public IActionResult OnPostLogin()
        {
            var email = Request.Form["email"];
            var password = Request.Form["password"];

            List<User> users = _context.User.ToList();

            foreach(var x in users)
            {
                if(x.Email == email && x.Password == password)
                {
                    // Set session variable for user ID
                    HttpContext.Session.SetInt32("UserID", x.UserID);

                    if(x.Admin)
                    {
                        _logger.LogInformation("Admin Logged In");
                        return RedirectToPage("/AdminPage");
                    }

                    _logger.LogInformation("Logged In");
                    return RedirectToPage("/HomePage");
                }              
                else if (x.Email == email && x.Password != password)
                {
                    _logger.LogInformation("Incorrect Password!");
                }
                else
                {
                    _logger.LogInformation("Incorrect email & Password!");
                }
            }

            return Page();
        }

        public IActionResult OnPostRegister()
        {
            var email = Request.Form["email"];
            var password = Request.Form["password"];

            List<User> users = _context.User.ToList();

            foreach (var x in users)
            {
                if (x.Email == email && x.Password == password)
                {
                    // Set session variable for user ID
                    HttpContext.Session.SetInt32("UserID", x.UserID);

                    if (x.Admin)
                    {
                        _logger.LogInformation("Admin Logged In");
                        return RedirectToPage("/AdminPage");
                    }

                    _logger.LogInformation("Logged In");
                    return RedirectToPage("/HomePage");
                }
                else if (x.Email == email && x.Password != password)
                {
                    _logger.LogInformation("Incorrect Password!");
                }
                else
                {
                    _logger.LogInformation("Incorrect email & Password!");
                }
            }

            return Page();
        }
    }
}

KhumaloCraft/Pages/MyWorkPage.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using KhumaloCraft.Models;
using KhumaloCraft.Data;
using Microsoft.Extensions.Configuration;

namespace KhumaloCraft.Pages
{
    public class MyWorkPageModel : PageModel
    {
        private readonly KhumaloCraftContext _context;
        private readonly ILogger<MyWorkPageModel> _logger;

        public MyWorkPageModel(KhumaloCraftContext context, ILogger<MyWorkPageModel> logger)
        {
            _context = context;
            _logger = logger;
        }

        public IList<Product> ProductList { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            ProductList = await _context.Product.ToListAsync();
            return Page();
        }


        public IActionResult OnPostAddToCart()
        {
            var product = int.Parse(Request.Form["productID"]);
            var quantity = int.Parse(Request.Form["quantity"]);
            var price = float.Parse(Request.Form["price"]);

            var salePrice = Math.Round(price * quantity, 2);

            int? userId = HttpContext.Session.GetInt32("UserID");
            
            int defaultUserId = userId ?? 1;

            var order = new Transactions
            {
                UserID = defaultUserId,
                ProductID = product,
                Quantity = quantity,
                SalePrice = salePrice,
                Processed = false
            };

            var remove = _context.Product.ToList();
            
            foreach (var x in remove)
            {
                if (x.ProductID == product)
                {
                    x.Quantity = x.Quantity - quantity;
                    _context.SaveChanges();
                }
            }

            _logger.LogInformation("Quantity : " + quantity.ToString());
            _logger.LogInformation("Price : " + price.ToString());

            _context.Transactions.Add(order);
            _context.SaveChanges();

            return RedirectToPage("/MyWorkPage");
        }

    }
}

KhumaloCraft/Pages/OrdersPage.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using KhumaloCraft.Data;
using KhumaloCraft.Models;

namespace KhumaloCraft.Pages
{
    public class OrdersPageModel : PageModel
    {
        private readonly KhumaloCraftContext _context;

        public OrdersPageModel(KhumaloCraftContext context)
        {
            _context = context;
        }

        public IList<OrderViewModel> Orders { get; set; }

        public async Task OnGetAsync()
        {
            // Get the user ID from session
            int? userId = HttpContext.Session.GetInt32("UserID");

            Orders = await _context.Transactions
                .Where(t => t.UserID == userId)
                .Join(
                    _context.Product,
                    transactions => transactions.ProductID,
                    product => product.ProductID,
                    (transactions, product) => new OrderViewModel
                    {
                        Quantity = transactions.Quantity,
                        SalePrice = transactions.SalePrice,
                        ProductName = product.Name,
                        Category = product.Category,
                        Processed = transactions.Processed
                    }
                )
                .ToListAsync();
        }

        public class OrderViewModel
        {
            public int Quantity { get; set; }
            public double SalePrice { get; set; }
            public string ProductName { get; set; }
            public string Category { get; set; }
            public bool Processed { get; set; }
            public string OrderStatus => Processed ? "Processed" : "Still processing";
        }
    }

}

KhumaloCraft/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KhumaloCraft.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

KhumaloCraft/Pages/RegisterPage.cshtml.cs
using KhumaloCraft.Data;
using KhumaloCraft.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace KhumaloCraft.Pages
{
    public class RegisterPageModel : PageModel
    {
        private readonly KhumaloCraftContext _context;
        private readonly ILogger<RegisterPageModel> _logger;

        public RegisterPageModel(KhumaloCraftContext context, ILogger<RegisterPageModel> logger)
        {
            _context = context;
            _logger = logger;
        }   

        public void OnGet()
        {

        }

        public IActionResult OnPostRegister()
        {
            var email = Request.Form["email"];
            var name = Request.Form["firstName"];
            var surname = Request.Form["lastName"];
            var password = Request.Form["password"];
            var passwordConfirm = Request.Form["confirmPassword"];

            string finalPassword = null;

            if (password != passwordConfirm)
            {
                return RedirectToPage("/RegisterPage");
            }
            else
            {
                finalPassword = password;
            }

            var user = new User
            {
                Email = email,
                Name = name,
                Surname = surname,
                Password = finalPassword,
                Admin = false

            };

            _context.User.Add(user);
            _context.SaveChanges();

            return RedirectToPage("/Index");
        }
    }
}

KhumaloCraft/Pages/AdminPage.cshtml
@page
@model KhumaloCraft.Pages.AdminPageModel
@{
}


<!DOCTYPE html>
<html>

<head>
    <title>Home Page</title>
    <style>

        body {
            font-family: Arial, sans-serif;
            background-image: url('/Images/background.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            margin: 0;
        }

        .header {
            text-align: center;
            font-size: 10rem;
            color: white;
            text-transform: uppercase;
            text-shadow: 2px 2px 2px #000;
        }

        h1 {
            text-align: center;
            font-size: 4rem;
            color: black;
            text-transform: uppercase;
            text-shadow: 2px 2px 2px white;
            font-family: 'Garamond', serif;
        }

        .navbar-nav .nav-item a {
            transition: color 0.3s, background-color 0.3s;
        }

            .navbar-nav .nav-item a:hover {
                color: darkblue;
                background-color: darkgrey;
            }

        .navbar {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            background-color: #fff;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
            z-index: 1000;
        }

        .navbar-nav {
            margin-top: 10px;
        }

        .navbar-brand {
            padding: 10px 15px;
        }

        .navbar-toggler {
            display: none;
        }

        .form-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 400px;
            width: 100%;
            margin: 0 auto;
        }

        input[type="text"],
        input[type="number"],
        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            padding: 10px 20px;
            cursor: pointer;
        }

            input[type="submit"]:hover {
                background-color: #0056b3;
            }

    </style>
</head>

<body>

    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/Index">LOG OUT</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <h1>ALL ORDERS</h1>

    <br />
    <br />
    <br />
    <br />
    <br />   
    <br />


    <table class="table">
        <thead>
            <tr>
                <th>Order ID</th>
                <th>User ID</th>
                <th>Product ID</th>
                <th>Quantity</th>
                <th>Sale Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var order in Model.Orders.Where(o => !o.Processed))
            {
                <tr>
                    <td>@order.TransactionID</td>
                    <td>@order.UserID</td>
                    <td>@order.ProductID</td>
                    <td>@order.Quantity</td>
                    <td>@order.SalePrice</td>
                    <td>
                        <form method="post" asp-page-handler="ProcessOrder">
                            <input type="hidden" name="id" value="@order.TransactionID" />
                            <button type="submit" name="processOrder" class="btn btn-primary">PROCESS ORDER</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

    </table>

    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <table class="table">

        <thead>
            <tr>
                <th>User ID</th>
                <th>E-Mail</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Admin Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var user in Model.users.Where(o => !o.Admin))
            {
                <tr>
                    <td>@user.UserID</td>
                    <td>@user.Email</td>
                    <td>@user.Name</td>
                    <td>@user.Surname</td>
                    <td>@user.Admin</td>
                    <td>
                        <form method="post" asp-page-handler="AdminStatus">
                            <input type="hidden" name="userid" value="@user.UserID" />
                            <button type="submit" name="makeadmin" class="btn btn-primary">MAKE ADMIN</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

    </table>

    <br />
    <br />
    <br />
    <br />

    <h1>All Items</h1>

    <br />
    <br />
    <br />

    <table class="table">

        <thead>
            <tr>
                <th>Product ID</th>
                <th>Product Name</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Category</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Products)
            {
                <tr>
                    <td>@product.ProductID</td>
                    <td>@product.Name</td>
                    <td>@product.Description</td>
                    <td>@product.Quantity</td>
                    <td>@product.Category</td>
                    <td>
                        <form method="post" asp-page-handler="DeleteProduct">
                            <input type="hidden" name="productid" value="@product.ProductID" />
                            <button type="submit" name="deleteproduct" class="btn btn-primary">DELETE ITEM</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

    </table>


    <h1>ADD ITEMS</h1>

    <br />
    <br />
    <br />
   
    <div class="form-container">
        <form method="post" asp-page-handler="AddItem">
            <input type="text" name="name" placeholder="Item Name" required>
            <input type="text" name="description" placeholder="Short Description" required>
            <input type="number" name="quantity" placeholder="Quantity" min="1" required>
            <input type="text" name="price" placeholder="Price per Item" required>
            <select name="category" required>
                <option value="" disabled selected>Select Category</option>
                <option value="Chairs">Chairs</option>
                <option value="Shelves">Shelves</option>
                <option value="Tables">Tables</option>
                <option value="Other">Other</option>
            </select>
            <input type="submit" value="Add Item">
        </form>
    </div>


</body>
</html>

KhumaloCraft/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}


<!DOCTYPE html>
<html>

<head>
    <title>Home Page</title>
    <style>

        body {
            font-family: Arial, sans-serif;
            background-image: url('/Images/spread.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            margin: 0;
        }

        .header {
            text-align: center;
            font-size: 10rem;
            color: white;
            text-transform: uppercase;
            text-shadow: 2px 2px 2px #000;
        }

        h1 {
            text-align: center;
            font-size: 4rem;
            color: black;
            text-transform: uppercase;
            text-shadow: 2px 2px 2px white;
            font-family: 'Garamond', serif;
        }

        img {
            width: 250px;
            height: auto;
            display: block;
            margin: 0 auto;
            border-radius: 25px;
        }

        .clickable-image {
            text-align: left;
        }

        .btn-container {
            text-decoration: none;
            display: block;
            transition: transform 0.3s, background-color 0.3s;
        }

        .btn-content {
            border: none;
            box-shadow: none;
            text-align: center;
            padding: 10px;
            padding-left: 10px;
            padding-right: 10px;
        }

        .btn-image {
            max-width: 125%;
        }

        .btn-container:hover .btn-content {
            transform: scale(1.3);
        }

        .login-container {
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
            max-width: 400px;
            width: 100%;
            margin: 0 auto;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 20px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 4px;
            padding: 10px 20px;
            cursor: pointer;
        }

            input[type="submit"]:hover {
                background-color: #0056b3;
            }

    </style>
</head>

<body>
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />   
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />
    <br />

    <div class="login-container">
        <h1>Login</h1>
        <form method="post"  asp-page-handler="Login">
            <input type="text" name="email" placeholder="E-Mail" required>
            <br>
            <input type="password" name="password" placeholder="Password" required>
            <br>
            <input type="submit" value="Login">
        </form>
        <br/>
        <div class="register-link">
            <p>Don't have an account? <a asp-page="/RegisterPage">Register here</a></p>
        </div>
    </div>

</body>

</html>

KhumaloCraft/Pages/MyWorkPage.cshtml
@page
@model KhumaloCraft.Pages.MyWorkPageModel
@{
}


<!DOCTYPE html>
<html>

<head>
    <title>My Work</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-image: url('/Images/background.jpg');
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            margin: 0;
            padding-top: 40px;
        }

        .header {
            text-align: center;
            font-size: 10rem;
            color: orange;
            text-transform: uppercase;
            text-shadow: 2px 2px 2px #000;
        }

        h1 {
            text-align: center;
            font-size: 4rem;
            color: black;
            text-transform: uppercase;
            text-shadow: 2px 2px 2px white;
            font-family: 'Garamond', serif;
        }

        .navbar-nav .nav-item a {
            transition: color 0.3s, background-color 0.3s;
        }

            .navbar-nav .nav-item a:hover {
                color: darkblue;
                background-color: darkgrey;
            }

        .navbar {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            background-color: #fff;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
            z-index: 1000;
        }

        .navbar-nav {
            margin-top: 10px;
        }

        .navbar-brand {
            padding: 10px 15px;
        }

        .navbar-toggler {
            display: none;
        }

        .work-container {
            display: flex;
            justify-content: center;
            flex-wrap: wrap;
            gap: 20px;
            padding: 20px;
        }

        .work-item {
            text-align: center;
            max-width: 300px;
        }

            .work-item img {
                max-width: 100%;
                border-radius: 10px;
            }

            .work-item h3 {
                margin-top: 10px;
                font-size: 1.5rem;
                font-family: 'Garamond', serif;
            }

            .work-item p {
                margin-top: 5px;
                font-size: 1.2rem;
                color: #666;
                font-family: 'Garamond', serif;
            }

        p {
            font-size: 1.75rem;
            line-height: 1.6;
            color: #333;
            font-family: 'Garamond', serif;
        }
    </style>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-page="/HomePage">HOME PAGE</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <br />
    <br />
    <br />

    <h1>MY WORK</h1>

    <br />
    <br />
    
    <p>
        Here are some of the handcrafted items that show the skill and level of quality that we aim to bring to KhumaloCraft.
    </p>

    <br />
    <br />

    <div class="work-container">
        @foreach (var product in Model.ProductList)
        {
            <div class="work-item">
                <img src="/Images/@(GetCategoryImage(product.Category))" alt="@product.Name">
                <h3>@product.Name</h3>
                <p>R @product.Price</p>
                <p>Units Left: @product.Quantity</p>
                <p>Category: @product.Category</p>
                @if (product.Quantity > 0)
                {
                    <form method="post" asp-page-handler="AddToCart">
                        <input type="hidden" name="productID" value="@product.ProductID" />
                        <input type="hidden" name="price" value="@product.Price" />
                        <input type="number" name="quantity" min="1" max="@product.Quantity" value="1" />
                        <button type="submit" class="btn btn-primary">Order Product</button>
                    </form>
                }
                else
                {
                    <p>Out of Stock</p>
                }
            </div>
        }
    </div>

    @functions {//will place the imaged based on which category it belongs to 
        public string GetCategoryImage(string category)
        {
            switch (category)
            {
                case "Tables":
                    return "table.jpg";
                case "Chairs":
                    return "chair.jpg";
                case "Shelves":
                    return "shelf.jpg";
                case "Other":
                    return "other.jpg";
                default:
                    return "other.jpg";
            }
        }
    }



</body>

</html>